In [5]:
import numpy as np

#Define a simple 5x5 grayscale image
image=np.array([
    [1,2,3,0,1],
    [0,1,2,3,2],
    [3,0,1,2,1],
    [1,3,2,0,1],
    [3,3,0,0,1]
])

#Define a 3x3 kernel(filter)
kernel=np.array([
    [0,1,0],
    [1,-4,0],
    [0,1,1]
])

#Define Convolutional Operation
def convolve(image,kernel):

  image_h,image_w=image.shape
  kernel_h,kernel_w=kernel.shape
  output_h=image_h-kernel_h+1
  output_w=image_w-kernel_w+1

  output=np.zeros((output_h,output_w))

  for i in range (output_h):
    for j in range (output_w):
      output[i,j]=np.sum(image[i:i+kernel_h,j:j+kernel_w]*kernel)
  return output

#Apply the convolution
output=convolve(image,kernel)
print("Convolution Output:\n",output)

Convolution Output:
 [[-1. -1. -7.]
 [ 9.  0. -3.]
 [-8. -4.  5.]]


**Padding With Stride**



*   Padding: Zero-padding is added to the image to control the spatial dimensions of the output.

*   Strides: Controls how much the filter moves at each step. A stride of 1 means the filter move 1 pixel at each time.

*   Convolution With Padding and Stride:The Output is now controlled by the padding and stride, allowing us to maintain or reduce the spatial dimensions of the output.






In [9]:
# Adding Padding
def pad_image(image,pad):
  return np.pad(image,pad,mode='constant',constant_values=0) #this numpy function will pad the image with 0 values
"""
[[1,2,3],                           [[0,0,0,0,0],
 [2,3,2],     ----> if pad=1 ===>>   [0,1,2,3,0],
 [2,1,3]]                            [0,2,3,2,0],
                                     [0,2,1,3,0],
                                     [0,0,0,0,0]]
"""

#Modify Convolution to add padding and strides
def Convolve_with_padding_and_stride(image,kernel,padding=0,stride=1):
  if padding>0:
    image=pad_image(image,padding)

  image_h,image_w=image.shape
  kernel_h,kernel_w=kernel.shape
  output_h=(image_h-kernel_h)//stride +1
  output_w=(image_w-kernel_w)//stride +1

  output=np.zeros((output_h,output_w))

  for i in range(0,stride*output_h,stride):
    for j in range(0,stride*output_w,stride):
      output[i//stride,i//stride]=np.sum(image[i:i+kernel_h,j:j+kernel_h] * kernel)

  return output

#Apply the Convolution
output=Convolve_with_padding_and_stride(image,kernel,padding=1)
print("Convolution Output:\n",output)


Convolution Output:
 [[-2.  0.  0.  0.  0.]
 [ 0. -3.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0. -2.  0.]
 [ 0.  0.  0.  0. -3.]]


**Pooling**



*   Pooling: It is a downsampling technique that reduces the spatial dimensions
 (heigh,width) of feature maps,preventing overfitting and creating tanslational invariance.




In [13]:
#Max Pooling
def max_pooling(image,poolsize,stride):
  image_h,image_w=image.shape
  output_h=(image_h-poolsize)//stride +1
  output_w=(image_w-poolsize)//stride +1
  output=np.zeros((output_h,output_w))

  for i in range(0,output_h*stride,stride):
    for j in range(0,output_w*stride,stride):
      output[i//stride,j//stride]=np.max(image[i:i+poolsize,j:j+poolsize])
  return output

feature_map=Convolve_with_padding_and_stride(image,kernel,padding=1)
output=max_pooling(feature_map,poolsize=2,stride=2)

print("Output after pooling:\n",output)




Output after pooling:
 [[0. 0.]
 [0. 1.]]


**Convolution On RGB Images**

In [19]:
#Define a simple 5x5x3 RGB Image(3 Channel)
image_rgb=np.array([
    [[1,0,2],[2,1,1],[3,2,0],[0,1,1],[1,0,2]],
    [[0,1,0],[1,0,1],[2,2,2],[3,1,3],[2,0,1]],
    [[3,0,2],[0,1,0],[1,0,1],[2,2,2],[1,0,0]],
    [[2,1,1],[1,0,2],[3,3,1],[0,1,0],[0,2,1]],
    [[1,2,2],[2,1,0],[0,0,1],[1,2,2],[2,1,1]]
])

#Define a 3x3x3 kernel(filter)
kernel_rgb=np.array([
    [[0,1,0],[1,-1,1],[0,1,0]],
    [[1,0,1],[0,-1,0],[1,0,1]],
    [[0,1,0],[1,1,1],[0,1,0]]
])

def convolve_rgb(image,kernel,):
  image_h,image_w,image_c=image.shape
  kernel_h,kernel_w,kernel_c=kernel.shape
  output_h=image_h-kernel_h+1
  output_w=image_w-kernel_h+1
  output=np.zeros((output_h,output_w))



  for i in range(output_h):
    for j in range(output_w):
      output[i,j]=np.sum(image[i:i+kernel_h,j:j+kernel_w]*kernel)
  return output

#Apply convolution
output=convolve_rgb(image_rgb,kernel_rgb)
print("Output of convolve_rgb:\n",output)

Output of convolve_rgb:
 [[ 9. 14. 14.]
 [18. 15. 14.]
 [11.  9. 12.]]


In [22]:
import tensorflow as tf
from tensorflow.keras import layers, models

#Example input shape for a 32x32 RGB Image
input_shape=(32,32,3)

# Define the model
model=models.Sequential()

#Add Input Layer
model.add(layers.Input(shape=input_shape))

#Adding Convolutional layer
model.add(layers.Conv2D(16,(3,3),padding='same',strides=1,activation='relu'))

#Adding Maxpooling layer
model.add(layers.MaxPooling2D(pool_size=(2,2),strides=2))

#Adding more convlutional layers and maxpooling layer
model.add(layers.Conv2D(32,(3,3),padding='same',strides=1,activation='relu'))
model.add(layers.MaxPooling2D(pool_size=(2,2),strides=2))

#print model summary to see the structure
model.summary()





Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_2 (Conv2D)               │ (None, 32, 32, 16)     │           448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 16, 16, 16)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 16, 16, 32)     │         4,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 8, 8, 32)       │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,088 (19.88 KB)

 Trainable params: 5,088 (19.88 KB)

 Non-trainable params: 0 (0.00 B)